spring:
  datasource:
    url: jdbc:mysql://172.21.1.40:3306/sbcp?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: sbcp
    password: sbcp
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  # 配置Mapper.xml映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
server:
  port: 8019
logging:
  file:
    name: logs/info.log